### ISSUE TITLE
Using nvals in GrB_Vector_extractTuples

### ISSUE THREAD

**Issue by szarnyasg** [GraphBLAS/LAGraph#45]
While testing #44 with LDBC Graphalytics, I discovered a problem in the LDBC glue code (implemented by @hegyibalint and myself). The cause of problem was that `GrB_Vector_extractTuples` uses `nvals` as both an input and an output:

![image](https://user-images.githubusercontent.com/1402801/69853172-65bca180-1286-11ea-9ecf-7c2ef7d1766a.png)

However, we [treated it as input only](https://github.com/FTSRG/ldbc-graphalytics-platform-graphblas/blob/e36690adfbd09cbfdd57cf5b9b024c4816d04d11/src/main/c/src/algorithms/wcc.cpp#L29-L33) and passed an uninitialized variable:

```cpp
GrB_Index nvals;

uint64_t *X = NULL;
X = (uint64_t *) LAGraph_malloc(n, sizeof(uint64_t));
OK(GrB_Vector_extractTuples_UINT64(GrB_NULL, X, &nvals, result));
```

Strangely, it worked fine in previous benchmark attempts, and it was also fine in most runs of the Boruvka-based CC algorithm. However, it crashed in some cases with the following error:
```console
terminate called after throwing an instance of 'std::runtime_error'
  what():  GraphBLAS error: GraphBLAS error: GrB_INSUFFICIENT_SPACE
function: GrB_Vector_extractTuples_UINT64 (I, X, nvals, v)
output arrays I,J,X are not big enough: nvals -4617319918479042816 < number of entries 9

/home/ubuntu/git/ldbc-graphalytics-platform-graphblas/graphalytics-1.3.0-graphblas-0.1-SNAPSHOT/./bin/sh/execute-job.sh: line 163: 77744 Aborted                 (core dumped) $COMMAND
```

Interestingly, this only happens in ~10% of the executions -- I guess in cases when the code reads garbage (a negative number?) from memory. I did 100 runs using the LDBC undirected example graph:

```bash
$ for i in `seq 1 100`; do
    echo $i
    /home/ubuntu/git/ldbc-graphalytics-platform-graphblas/graphalytics-1.3.0-graphblas-0.1-SNAPSHOT/./bin/sh/execute-job.sh --job-id r667354 --log-path /home/ubuntu/git/ldbc-graphalytics-platform-graphblas/graphalytics-1.3.0-graphblas-0.1-SNAPSHOT/report/191128-180611-GRAPHBLAS-report-CUSTOM/log/r667354-WCC-example-undirected/platform --directed false --algorithm wcc --input-path ./intermediate/example-undirected --output-path /home/ubuntu/git/ldbc-graphalytics-platform-graphblas/graphalytics-1.3.0-graphblas-0.1-SNAPSHOT/./output/r667354-WCC-example-undirected/r667354-WCC-example-undirected --num-threads 104
  done 2>&1 | tee wcc.log
```

There were 10 crashes:
```bash
$ cat wcc.log | grep INSUFFICIENT | wc -l
10
```

Initializing `nvals` as follows fixed the issue - there were no crashes in 10,000 runs.

```cpp
GrB_Vector_nvals(&nvals, result);
```

So while this is definitely not a bug, using the API incorrectly results in non-deterministic behaviour which can potentially go unnoticed for a long time. Right now, I don't see any trivial way to make this easier to notice.

What do you think @DrTimothyAldenDavis ?

**Comment by DrTimothyAldenDavis** [comment]
The design of the nvals argument, as being both input and output, comes
from the spec.  I would have preferred a different API, where the parameter
is a read-only input parameter, since I was concerned about this possible
situation, but that's what the GraphBLAS API committee settled on.

All I do on input is to check to make sure that the X and I arrays are
large enough.  The input nvals must be larger than the actual # of entries
in the matrix or vector.  This is to ensure that the output fits into the
user arrays.

Then on output, I return the number of entries actually extracted.

The code you pointed to is using nvals as an output-only variable,
returning the number of entries actually extracted.  It's not an input-only
variable in that code, but treated as an output-only variable.

That will lead to undefined behavior, and I can't correct for this inside
GraphBLAS.  If nvals is passed in uninitialized, I can't tell that it is
invalid.  All I do is to check to see that the input value of nvals (which
tells me the size of the arrays X and I) is at least as big as the # of
entries in the matrix or vector.  If the value is garbage, this test is
indeterminate, and there's nothing I can do to mitigate against this.

My preference was to make this parameter not a pointer, but a plain
integer, so it would be an input-only value.  It would just tell me the
size of the input arrays, like snprintf.  Then the # of entries returned in
the arrays could be obtained by GrB_Vector_nvals, if desired.  I was
worried that using nvals as both input and output might cause exactly this
sort of confusion.

**Comment by szarnyasg** [comment]
Thanks for this answer - it seems there isn't much to do outside the realms of the API. I'm closing this issue.
