### ISSUE TITLE
malloc.h was presumably removed in MacOS 10.14

### ISSUE THREAD

**Issue by michelp** [GraphBLAS/LAGraph#69]
Still tracking this issue down but LAGraph_init includes malloc.h which is deprecated, and now seemingly removed from MacOSX 10.14.

The general advice on the internet is to use stdlib.h instead, but that does not define malopt.  I cannot get a definitive answer on where malopt is found on newer OSX. 

So maybe the answer is to include guard malloc.h and the use on malopt to be only on linux.

This was based on an issue reported by @szarnyasg at https://github.com/michelp/pygraphblas/issues/19

**Comment by DrTimothyAldenDavis** [comment]
OK.  Yes, we should add an #ifdef so that is only done on Linux.  The
malloc options turned out to be exceedingly important for the performance
of LAGraph+GraphBLAS on the GAP benchmarks.  Without it, a large problem
might spend 20% of its total runtime just freeing its internal workspace,
using (say) GrB_free.  With the malloc options set as they are in
LAGraph_init, the GrB_free time goes to essentially zero.

**Comment by michelp** [comment]
I tried fixing this with #71, that I adapted from your travis.yml you linked above.  It works, although clang throws a lot of warnings about not understanding GCC warning pragmas, the one hour build limit applies to both builds running simultaneously, and it doesn't make it past 30 minutes.  So I've commented out osx for now and will get it working on linux.
